#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adam-stedi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adam-stedi
  template:
    metadata:
      labels:
        app: adam-stedi
    spec:
      containers:
        - name: adam-stedi
          image: gcr.io/teca-350016/stedi-adam:latest
          command: ["npm"]
          args: ["run","start"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: adam-stedi-loadbalancer
spec:
  selector:
    app: adam-stedi
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
